### PR TITLE
Add ability to create `Proj`s from EPSG codes.

### PR DESCRIPTION
**Pull request by frewsxcv**
Using a crate I recently created: https://github.com/frewsxcv/crs-definitions

### CODE REVIEW

**Comment by dmarteau** [comment]
@frewsxcv  nice addition

Maybe you could add some tests.

**Comment by dmarteau** [comment]
@frewsxcv I'd like to merge this, could I add a test and even a example ?  thanks.

**Comment by frewsxcv** [comment]
@dmarteau I already have an example and a test in the example

Screenshot 2023-11-19 at 1 14 55 PM

Can you share more about what you would like tested?

**Comment by dmarteau** [comment]
> I already have an example and a test in the example

Ho, I missed that, thanks.

**Review by dmarteau — APPROVED** [review]

**Pull request merged**
