### PR TITLE
Removed debug call in console

### PR DESCRIPTION
**Pull request by neo-garaix**
* Deleted the debug call to get a clean demo

### CODE REVIEW

**Comment by Gustry** [comment]
FYI, I have fixed the CI about the documentation, if you rebase, it will be green.

I'm not sure you need to make a tag in the changelog, as no "rust" code is updated.

**Comment by neo-garaix** [comment]
> FYI, I have fixed the CI about the documentation, if you rebase, it will be green.
> 
> I'm not sure you need to make a tag in the changelog, as no "rust" code is updated.

Great, it worked ! Thanks !

**Comment by dmarteau** [comment]
Why would you remove debug log ? the actual purpose of this is...debugging

**Comment by neo-garaix** [comment]
René Luc told me to remove it because he was thinking it was bit "too much" in the console but we can keep it.

**Comment by dmarteau** [comment]
It should stay, this is debug purpose, and usually people don't look at  the console except for...debugging.

**Pull request closed without merging**
